# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-15 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('recipients', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('interval', models.IntegerField()),
                ('time', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='status',
            field=models.CharField(choices=[('s', 'showing'), ('h', 'hidden')], default='h', max_length=1),
        ),
    ]
