# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-07 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
