# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-16 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20180515_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtasks',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtasks',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailtasks',
            name='interval',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emailtasks',
            name='task_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
