# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-09 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20180509_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
