# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-16 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20180516_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtasks',
            name='last_run_at',
        ),
        migrations.RemoveField(
            model_name='emailtasks',
            name='next_run_at',
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='status',
            field=models.CharField(choices=[('h', 'hidden'), ('s', 'showing')], default='h', max_length=1),
        ),
    ]
