# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-17 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20180517_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='status',
            field=models.CharField(choices=[('s', 'showing'), ('h', 'hidden')], default='h', max_length=1),
        ),
    ]
