# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-09 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20180509_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='email',
            field=models.EmailField(help_text='Enter your email', max_length=254),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='question',
            field=models.TextField(help_text='Enter any question'),
        ),
    ]
