# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-17 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedchecks',
            name='notification_priority',
            field=models.CharField(default='first tier', max_length=50),
        ),
    ]
