# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assignedchecks_notification_priority'),
        ('api', '0002_assignedchecks_notofication_priority'),
    ]

    operations = [
    ]
